name: password_manager_auth
description: 2FA (TOTP) utilities.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.11.0
  otp: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
