import Foundation
import Testing
@testable import PasswordManageriOSCore

@Suite("Dart crypto compatibility fixture")
struct DartCompatibilityFixtureTests {
    @Test("Swift derives and decrypts a fixture generated by packages/crypto")
    func decryptsDartGeneratedFixture() throws {
        let fixture = try loadFixture()
        let crypto = VaultCryptoService()
        let salt = try #require(Data(base64Encoded: fixture.saltBase64))
        let expectedKey = try #require(Data(base64Encoded: fixture.derivedKeyBase64))
        let metadataSalt = try #require(Data(base64Encoded: fixture.metadataSaltBase64))
        let expectedMetadataKey = try #require(Data(base64Encoded: fixture.metadataDerivedKeyBase64))

        let derivedKey = try crypto.deriveKeyForTesting(
            password: fixture.password,
            salt: salt,
            iterations: fixture.iterations
        )
        let metadataKey = try crypto.deriveKeyForTesting(
            password: fixture.password,
            salt: metadataSalt,
            iterations: fixture.iterations
        )
        let plaintext = try crypto.decrypt(fixture.encryptedPayload, key: derivedKey)
        let plaintextString = try #require(String(data: plaintext, encoding: .utf8))
        let repository = FileVaultRepository(
            baseDirectory: FileManager.default.temporaryDirectory
                .appendingPathComponent("PasswordManagerMacOSFixture-\(UUID().uuidString)")
        )
        let snapshot = try repository.decodeSnapshot(plaintext)
        let credentialEntry = try #require(snapshot.entries.first { $0.type == .credential && !$0.isDeleted })
        let serverEntry = try #require(snapshot.entries.first { $0.type == .server })
        let serviceEntry = try #require(snapshot.entries.first { $0.type == .service })
        let tombstoneEntry = try #require(snapshot.entries.first { $0.isDeleted })

        #expect(fixture.iterations == VaultCryptoService.defaultIterations)
        #expect(derivedKey == expectedKey)
        #expect(metadataKey == expectedMetadataKey)
        #expect(plaintextString == fixture.plaintextUtf8)
        #expect(snapshot.entries.count == 4)
        #expect(snapshot.categories == ["Archive", "Compatibility", "Infrastructure", "Services"])
        #expect(snapshot.tags == ["dart", "deleted", "fixture", "ops", "prod", "server", "service"])
        #expect(snapshot.security.requireTotp)
        #expect(snapshot.security.totpSecret == "JBSWY3DPEHPK3PXP")
        #expect(snapshot.syncStatus == "Fixture sync idle")
        #expect(snapshot.lastBackupStatus == "No backup has run")
        #expect(credentialEntry.id.uuidString.lowercased() == "11111111-2222-3333-4444-555555555555")
        #expect(credentialEntry.label == "Dart Fixture Credential")
        #expect(credentialEntry.payload.category == "Compatibility")
        #expect(credentialEntry.payload.tags == ["fixture", "dart"])
        #expect(credentialEntry.version == ["dart-fixture": 1])
        #expect(credentialEntry.updatedBy == "dart-fixture")

        guard case .credential(let credential) = credentialEntry.payload else {
            Issue.record("Expected credential payload")
            return
        }
        #expect(credential.username == "fixture-user")
        #expect(credential.password == "fixture-password")
        #expect(credential.token == "fixture-token")
        #expect(credential.appId == "fixture-app")
        #expect(credential.accessKey == "fixture-access-key")
        #expect(credential.secretKey == "fixture-secret-key")
        #expect(credential.notes == "fixture-note")

        #expect(serverEntry.id.uuidString.lowercased() == "22222222-3333-4444-5555-666666666666")
        #expect(serverEntry.label == "Dart Fixture Server")
        #expect(serverEntry.payload.category == "Infrastructure")
        #expect(serverEntry.payload.tags == ["server", "ops"])
        guard case .server(let server) = serverEntry.payload else {
            Issue.record("Expected server payload")
            return
        }
        #expect(server.name == "fixture-server")
        #expect(server.ipAddress == "10.0.0.12")
        #expect(server.port == "22")
        #expect(server.username == "root")
        #expect(server.password == "server-password")
        #expect(server.basicConfig == "2CPU 4GB")
        #expect(server.operatingSystem == "Ubuntu 24.04")
        #expect(server.location == "rack-a")
        #expect(server.notes == "server-note")
        #expect(server.accountId == "11111111-2222-3333-4444-555555555555")

        #expect(serviceEntry.id.uuidString.lowercased() == "33333333-4444-5555-6666-777777777777")
        #expect(serviceEntry.label == "Dart Fixture Service")
        #expect(serviceEntry.payload.category == "Services")
        #expect(serviceEntry.payload.tags == ["service", "prod"])
        guard case .service(let service) = serviceEntry.payload else {
            Issue.record("Expected service payload")
            return
        }
        #expect(service.name == "fixture-service")
        #expect(service.connectionAddress == "service.internal")
        #expect(service.connectionPort == "443")
        #expect(service.accountId == "11111111-2222-3333-4444-555555555555")
        #expect(service.serverIds == ["22222222-3333-4444-5555-666666666666"])
        #expect(service.accounts.count == 1)
        #expect(service.accounts.first?.username == "svc-admin")
        #expect(service.accounts.first?.password == "svc-password")
        #expect(service.accounts.first?.note == "primary service account")
        #expect(service.notes == "service-note")

        #expect(tombstoneEntry.id.uuidString.lowercased() == "44444444-5555-6666-7777-888888888888")
        #expect(tombstoneEntry.label == "Dart Fixture Tombstone")
        #expect(tombstoneEntry.isDeleted)
        #expect(tombstoneEntry.deletedAt != nil)
        #expect(tombstoneEntry.version == ["dart-fixture": 4])
    }

    private func loadFixture() throws -> DartCryptoFixture {
        let url = Bundle.module.url(
            forResource: "dart_crypto_fixture",
            withExtension: "json"
        )
        let fixtureURL = try #require(url)
        let data = try Data(contentsOf: fixtureURL)
        let decoder = JSONDecoder()
        return try decoder.decode(DartCryptoFixture.self, from: data)
    }
}

private struct DartCryptoFixture: Decodable {
    var password: String
    var iterations: Int
    var saltBase64: String
    var metadataSaltBase64: String
    var derivedKeyBase64: String
    var metadataDerivedKeyBase64: String
    var plaintextUtf8: String
    var encryptedPayload: EncryptedPayloadRecord
}
